// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_expiredate_LicenceTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_expiredate_LicenceTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712140933238_add_expiredate_LicenceTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
