// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updates_From_Victor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates_From_Victor));
        
        string IMigrationMetadata.Id
        {
            get { return "201712210533056_Updates_From_Victor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
