// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_ActivityDealer_and_RefServiceCategory_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_ActivityDealer_and_RefServiceCategory_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201712180705589_Update_ActivityDealer_and_RefServiceCategory_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
