// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_required_decoration_ref_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_required_decoration_ref_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201712190126273_update_required_decoration_ref_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
