// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class After_merger_applicants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After_merger_applicants));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040242134_After_merger_applicants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
