// <auto-generated />
namespace Misitu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tp_and_tpitems_fields_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tp_and_tpitems_fields_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101359501_tp_and_tpitems_fields_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
